POST  http://localhost:8088/api/auth/sign-up
Content-Type: application/json

{
    "username":"Karmegam",
    
    "email":"karmegam232734@gmail.com",
    "password":"hello1234"
}
###
POST  http://localhost:8088/api/auth/sign-in
Content-Type: application/json

{
    "email":"karmegam232734@gmail.com",
    "password":"hello1234"
}